/**
 * logitMaskGenerator.ts
 *
 * Substory 2.3: Logit masking for AST node types.
 *
 * Takes a context window of tokens (from subvocal-large's KV Cache or input sequence)
 * and filters them based on their associated AST tag. Only tokens whose tag matches
 * the allowed node types are returned, effectively "masking" out unwanted tokens
 * by zeroing their logits before softmax.
 *
 * This enables alignment between subvocal-large's token selection and the
 * actual, structured content injected by injectASTTags.
 */

import type { ASTTagResult, injectASTTags } from './astTagger.js';

export interface LogitMaskConfig {
  /** Set of AST node types to allow (wildcard '*' permits all tokens). */
  allowedNodeTypes: Set<string>;
  /** Token IDs from the current context window (e.g., from a previous tokenization step). */
  contextTokens: Int32Array;
  /** Map from tokenId to nodeLabel (as generated by injectASTTags). */
  tagMap: Map<number, string>;
}

/**
 * Generate a logit mask (set of allowed token IDs) based on AST node types.
 * This enables AST-Forced Speculation where only tokens associated with
 * allowed AST node types can be sampled, forcing the model to stay within
 * syntactically valid boundaries.
 *
 * @param config.allowedNodeTypes - Set of AST node types to permit (e.g., 'function_declaration', 'class_declaration')
 * @param config.contextTokens - All token IDs in the current context
 * @param config.tagMap - Mapping from Token ID → node label (from injectASTTags)
 * @returns Int32Array of allowed token IDs (only those matching allowed AST node types)
 */
export function generateLogitMaskForASTNodes(
  config: LogitMaskConfig,
): Int32Array {
  const { allowedNodeTypes, contextTokens, tagMap } = config;

  const result: number[] = [];

  for (let i = 0; i < contextTokens.length; i++) {
    const tokenId = contextTokens[i];
    const tag = tagMap.get(tokenId);

    if (!tag) {
      continue;
    }

    // Empty allowed set = allow all (fallback)
    if (allowedNodeTypes.size === 0) {
      result.push(tokenId);
      continue;
    }

    // Wildcard '*' permits all tokens
    if (allowedNodeTypes.has('*')) {
      result.push(tokenId);
      continue;
    }

    // Check if tag matches any allowed node type
    for (const allowedType of allowedNodeTypes) {
      // Exact match or prefix match (e.g., 'function_declaration' matches 'function_declaration:foo')
      if (tag === allowedType || tag.startsWith(allowedType + ':')) {
        result.push(tokenId);
        break;
      }
    }
  }

  return new Int32Array(result);
}