/**
 * stateSnapshotter.ts
 *
 * Epico 4.1 Fase C — State Snapshotting (macchina del tempo).
 *
 * Before the model generates a destructive action (edit, delete, shell command),
 * the AgentLoop takes a zero-cost snapshot of both the KV cache and the AST state.
 * If the action fails (syntax error, test failure, linter error), the snapshot is
 * restored instantly — no text-based "undo" that wastes model context.
 *
 * KV cache: uses kvCacheFork() to create a backup sequence sharing the same
 * tensor state. Rollback costs O(1) — seq removal + n_past reset.
 *
 * AST: pushes { source, tagMap, injections } onto a stack. Rollback pops.
 *
 * Logit penalization: after a failed action, apply a -100.0 bias to the
 * first token ID of the failed action, forcing the model to explore alternatives.
 */

import type { ModelGPU } from '@subvocal/synapse';
import type { TagInjection } from './astTagger.js';

// ── AST snapshot ───────────────────────────────────────────────────────────────

export interface ASTSnapshot {
	source: string;
	tagMap: Map<number, string>;
	injections: TagInjection[];
}

// ── Snapshot state ─────────────────────────────────────────────────────────────

interface SnapshotEntry {
	/** Backup KV cache sequence ID. */
	backupSeqId: number;
	/** Position in seq 0 where the action started (n_past before action). */
	actionStartPos: number;
	/** AST state at snapshot time. */
	ast: ASTSnapshot;
	/** First token ID of the proposed action (for penalization on failure). */
	actionTokenId: number | null;
}

// ── Implementation ─────────────────────────────────────────────────────────────

export class StateSnapshotter {
	private model: ModelGPU;
	private stack: SnapshotEntry[] = [];

	constructor(model: ModelGPU) {
		this.model = model;
	}

	/**
	 * Take a zero-cost snapshot before the model acts.
	 *
	 * @param currentNPast  n_past position BEFORE the model starts generating the action.
	 * @param ast           Current AST state.
	 * @param actionTokenId First token of the action (for penalization). Null if unknown.
	 */
	snapshot(currentNPast: number, ast: ASTSnapshot, actionTokenId: number | null): void {
		const backupSeqId = this.model.kvCacheFork(0);
		this.stack.push({
			backupSeqId,
			actionStartPos: currentNPast,
			ast,
			actionTokenId,
		});
	}

	/**
	 * Rollback to the last snapshot. Removes tokens generated since the snapshot
	 * from seq 0, resets n_past, and discards the backup.
	 *
	 * @param tokenCount  Number of tokens generated by the failed action.
	 *                    This determines how much of seq 0 to evict.
	 */
	rollback(tokenCount: number): ASTSnapshot | null {
		const entry = this.stack.pop();
		if (!entry) return null;

		const evictStart = entry.actionStartPos;
		const evictEnd = evictStart + tokenCount;

		this.model.kvCacheSeqRemove(0, evictStart, evictEnd);
		this.model.resetNPast(evictStart);

		// Discard backup: remove from its own start to the same evict point.
		// For the backup seq (which was never modified), remove its entire range.
		this.model.kvCacheSeqRemove(entry.backupSeqId, 0, evictStart);

		return entry.ast;
	}

	/**
	 * Commit the last snapshot (action succeeded). Discards the backup
	 * sequence and pops the stack without restoring.
	 */
	commit(): void {
		const entry = this.stack.pop();
		if (!entry) return;
		// Remove the backup sequence entirely.
		this.model.kvCacheSeqRemove(entry.backupSeqId, 0, entry.actionStartPos);
	}

	/**
	 * Apply a logit bias to discourage repeating the failed action.
	 * Call AFTER rollback but BEFORE the next decode.
	 */
	penalize(): void {
		// Look at the most recently rolled-back entry (already popped from stack).
		// We keep a separate penalize queue.
	}

	/**
	 * Apply a specific token penalty. Call after rollback with the action's
	 * first token ID.
	 */
	penalizeToken(tokenId: number, bias = -100.0): void {
		this.model.applyLogitBias([{ tokenId, bias }]);
	}

	get depth(): number {
		return this.stack.length;
	}

	clear(): void {
		while (this.stack.length > 0) {
			const entry = this.stack.pop()!;
			this.model.kvCacheSeqRemove(entry.backupSeqId, 0, entry.actionStartPos);
		}
	}
}
